### ISSUE TITLE
How to modify qp num between client and server in toml？

### ISSUE THREAD

**Issue by WoShiAPei** [deepseek-ai/3FS#228]
Many Thanks!

**Comment by SF-Zhou** [comment]
For fuse, you can modify `max_connections`:

```toml
[storage.net_client.io_worker.transport_pool]
max_connections = 1
```
